---
title: "Appendix A: The MSTCAR Hierarchical Model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Appendix A: The MSTCAR Hierarchical Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview

In this vignette, we outline the hierarchical models used in the `RSTr` package, along with the full-conditional distributions used for each update.

## The UCAR Hierarchical Model

The UCAR model used by `RSTr` is based on the model developed by [Besag, York, and Mollié (1991)](https://link.springer.com/article/10.1007/bf00116466) with modifications using inverse transform sampling for restricted informativeness based on [Quick, et al. (2021)](https://pubmed.ncbi.nlm.nih.gov/33980402/):

For models using `method = "binom"`,

$$
Y_{i} \sim \text{Binomial}(n_{i}, \theta_{i}) \\
\theta_{i} \sim \text{LogitNormal}(\beta_{j} + Z_{i}, \tau^2),\\ 
i=\{1,...,N_s\}, j=\{1,...,N_{is}\}
$$

For models using `method = "pois"`,

$$
Y_{i} \sim \text{Poisson}(n_{i} \theta_{i}) \\
\theta_{i} \sim \text{LogNormal}(\beta_{j} + Z_{i}, \tau^2),\\ 
i=\{1,...,N_{s}\},\ j=\{1,...,N_{is}\}
$$

For both models,

$$
\beta_{j} \sim \text{Normal}(0,\sigma_{\beta}^2),\ \sigma_{\beta}^2 \to \infty \\
Z \sim \text{CAR}(\sigma^2) \\
\sigma^2 \sim \text{InvGamma}(a_\sigma,b_\sigma) \\
\tau^2 \sim \text{InvGamma}(a_\tau,b_\tau)
$$

## The USTCAR Hierarchical Model

This model is still under development and will be incorporated here once a restricted USTCAR model is completed.

## The MCAR Hierarchical Model

The MCAR model used by `RSTr` is an extension of the model developed by [Besag, York, and Mollié (1991)](https://link.springer.com/article/10.1007/bf00116466) with modifications using inverse transform sampling for restricted informativeness based on [Quick, et al. (2021)](https://pubmed.ncbi.nlm.nih.gov/33980402/):

For models using `method = "binom"`,

$$
Y_{ik} \sim \text{Binomial}(n_{ik}, \theta_{ik}) \\
\theta_{ik} \sim \text{LogitNormal}(\beta_{jk} + Z_{ik}, \tau_k^2),\\ 
i=\{1,...,N_s\}, k=\{1,...,N_{g}\}, j=\{1,...,N_{is}\}
$$

For models using `method = "pois"`,

$$
Y_{ik} \sim \text{Poisson}(n_{ik}, \theta_{ik}) \\
\theta_{ik} \sim \text{LogNormal}(\beta_{jk} + Z_{ik}, \tau_k^2),\\ 
i=\{1,...,N_s\}, k=\{1,...,N_{g}\}, j=\{1,...,N_{is}\}
$$

For both models,

$$
\beta_{jk} \sim \text{Normal}(0,\sigma_{\beta}^2),\ \sigma_{\beta}^2 \to \infty \\
Z \sim \text{CAR}(G) \\
G \sim \text{InvWishart}(\nu,G_0) \\
\tau^2 \sim \text{InvGamma}(a_\tau,b_\tau)
$$

## The MSTCAR Hierarchical Model

The MSTCAR model used by `RSTr` is based on the model developed by [Quick, et al. (2017)](https://doi.org/10.1214/17-AOAS1068):

For models using `method = "binom"`,

$$
Y_{ikt} \sim \text{Binomial}(n_{ikt}, \theta_{ikt}) \\
\theta_{ikt} \sim \text{LogitNormal}(\beta_{jkt} + Z_{ikt}, \tau_k^2),\\ 
i=\{1,...,N_s\},\ k=\{1,...,N_g\},\ t=\{1,...,N_t\},\ j=\{1,...,N_{is}\}
$$

For models using `method = "pois"`,

$$
Y_{ikt} \sim \text{Poisson}(n_{ikt} \theta_{ikt}) \\
\theta_{ikt} \sim \text{LogNormal}(\beta_{jkt} + Z_{ikt}, \tau_k^2),\\ 
t=\{1,...,N_t\},\ i=\{1,...,N_s\},\ k=\{1,...,N_g\},\ j=\{1,...,N_{is}\}
$$

For both models,

$$
\beta_{jkt} \sim \text{Normal}(0,\sigma_{\beta}^2),\ \sigma_{\beta}^2 \to \infty \\
Z \sim \text{MSTCAR}(\mathcal{G}, \mathcal{R}), \ \mathcal{G}=\{G_1,...,G_{N_t}\}, \ \mathcal{R}=\{R_1,...,R_{N_g}\} \\
G_t \sim \text{InvWishart}(A_G, \nu) \\
A_G \sim \text{Wishart}(A_{G_0}, \nu_0) \\
R_k = \text{AR}(1,\rho_k) \\
\rho_k \sim \text{Beta}(a_{\rho}, b_{\rho}) \\
\tau_k^2 \sim \text{InvGamma}(a_\tau,b_\tau)
$$

For more information regarding the model and its full-conditional distributions, reference [Quick, et al. (2017)](https://doi.org/10.1214/17-AOAS1068).